services:

  xray-config:
    build:
      context: ./xray-config
      dockerfile: Dockerfile
    restart: always
    env_file:
      - env_file
    environment:
      - TZ=UTC
    volumes:
      - "/etc/machine-id:/host/etc/machine-id"
      - "acme:/root/.acme.sh/"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  xray:
    build:
      context: ./xray
      dockerfile: Dockerfile
    volumes:
      - "/var/log:/var/log"
    cap_add:
      - NET_ADMIN
    restart: always
    env_file:
      - env_file
    environment:
      - TZ=UTC
    depends_on:
      - xray-config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "443:443/tcp"
      - "443:443/udp"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - "acme:/root/.acme.sh/"
      - "/var/log:/var/log"
    restart: always
    env_file:
      - env_file
    ports:
      - "80:80/tcp"
      - "2053:2053/tcp"
      - "2053:2053/udp"
      - "2083:2083/tcp"
      - "2083:2083/udp"
      - "8443:8443/tcp"
      - "8443:8443/udp"
    environment:
      - TZ=UTC
    depends_on:
      - xray
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  v2ray-exporter:
    build:
      context: ./v2ray-exporter
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - xray

  user-metrics:
    build:
      context: ./user-metrics
      dockerfile: Dockerfile
    volumes:
      - "/var/log:/var/log:ro"
    restart: always
    environment:
      - TZ=UTC
    depends_on:
      - xray
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "127.0.0.1:9551:9551"

  metric-forwarder:
    build:
      context: ./metric-forwarder
      dockerfile: Dockerfile
    restart: always
    env_file:
      - env_file
    environment:
      - TZ=UTC
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - xray-config
      - node-exporter

  node-exporter:
    image: prom/node-exporter:v1.9.1
    restart: always
    network_mode: host
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=UTC
    command:
      - "--log.level=warn"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - '--collector.disable-defaults'
      - '--collector.uname'
      - '--collector.cpu'
      - '--collector.meminfo'
      - '--collector.filesystem'
      - '--collector.netdev'
      - '--collector.time'
      - '--collector.stat'
      - '--collector.pressure'
      - "--web.listen-address=172.17.0.1:9100" # only allow access from host.docker.internal interface
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  fail2ban:
    build:
      context: ./fail2ban
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/var/log:/var/log:ro"
      - "./fail2ban/jail.d:/etc/fail2ban/jail.d:ro"
      - "./fail2ban/jail.local:/etc/fail2ban/jail.local:ro"
      - "./fail2ban/filter.d:/etc/fail2ban/filter.d:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  acme:
